### ISSUE TITLE
Не могу запустить

### ISSUE THREAD

**Issue by andromedakroos** [Gladn/HtmlParser#1]
Привет, хотел запустить твой проект, так как это тема моего курсача, но не получается, я так понял, что не хватает мейна, не мог бы ты его залить на гитхаб, заранее спасибо!

**Comment by Gladn** [comment]
MainWindow.Xaml.cs эт мейн, можно как то конкретнее?

**Comment by Gladn** [comment]
![изображение](https://user-images.githubusercontent.com/92585647/168191060-ec447763-84ac-4c91-9050-e9a93d45372a.png)
![изображение](https://user-images.githubusercontent.com/92585647/168190931-bd637f26-915e-472b-b0c9-8b85c4efa14a.png)
Открыл VS проект сразу через github

**Comment by andromedakroos** [comment]
Окей, попробую, спасибо

**Comment by andromedakroos** [comment]
Да, все ок, спасибо :)
